config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/author'

  get 'static_pages/help'

  root to: 'static_pages#home'
  match '/about', to:"static_pages#about", via:'get'
  match '/author', to:"static_pages#author", via:'get'
  match '/help', to:"static_pages#help", via:'get'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
    base_title = "时间猎人"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "时间猎人", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "首页",    root_path %></li>
          <li><%= link_to "帮助",    help_path %></li>
          <li><%= link_to "关于", about_path %></li>
          <li><%= link_to "作者", author_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<div class="container">
	<iframe width="100%" height="550" class="share_self"  frameborder="0" scrolling="no" src="http://widget.weibo.com/weiboshow/index.php?language=&width=0&height=550&fansRow=2&ptype=0&speed=0&skin=1&isTitle=1&noborder=1&isWeibo=1&isFans=1&uid=2113020163&verifier=64e7ae81&dpc=1"></iframe>
</div>

<p>
asdf
</p>

app/views/static_pages/author.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<div class="container">
	<h1>
	作者信息：<a href="http://www.dzpqzb.com">个人博客</a>
</h1>
</div>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, '首页') %>

<div class="center hero-unit">
	<h1>时间猎人</h1>
	<p>时间都去哪里了？</p>
</div>